[package]
name = "oxide"
version = "0.1.0"
authors = ["Erwan <erwan.delepinau@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
